-- ============================================================================
-- MIGRACIÓN: IDs Autoincrementales, Estado y Soft Delete
-- Fecha: 2026-08-25
-- Nota: Esta migración recreará las tablas para cambiar de UUID a BIGINT.
-- Asegúrese de respaldar si hay datos en producción.
-- ============================================================================

-- Deshabilitar constraints temporalmente si fuera necesario, 
-- pero dado que cambiaremos UUID por BIGINT, la forma más limpia 
-- es eliminar las tablas en orden y recrearlas.

DROP TABLE IF EXISTS public.facturas CASCADE;
DROP TABLE IF EXISTS public.alquiler_detalles CASCADE;
DROP TABLE IF EXISTS public.alquileres_detalle CASCADE;
DROP TABLE IF EXISTS public.alquileres CASCADE;
DROP TABLE IF EXISTS public.equipos CASCADE;
DROP TABLE IF EXISTS public.items CASCADE;
DROP TABLE IF EXISTS public.clientes CASCADE;
DROP TABLE IF EXISTS public.logs_sistema CASCADE;

-- 1. TABLA CLIENTES
CREATE TABLE public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nit_cedula VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    telefono VARCHAR(50),
    email VARCHAR(150),
    direccion TEXT,
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL,
    deleted_by VARCHAR(100) NULL
);

CREATE INDEX idx_clientes_busqueda ON public.clientes (nit_cedula, nombre) WHERE estado = 'Activo' AND deleted_at IS NULL;
CREATE INDEX idx_clientes_deleted ON public.clientes (deleted_at);

-- 2. TABLA EQUIPOS (BODEGA)
CREATE TABLE public.equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    tarifa_diaria NUMERIC(12, 2) NOT NULL CHECK (tarifa_diaria >= 0),
    stock_total INT NOT NULL CHECK (stock_total >= 0),
    stock_disponible INT NOT NULL CHECK (stock_disponible >= 0),
    stock_en_obra INT NOT NULL CHECK (stock_en_obra >= 0),
    stock_mantenimiento INT NOT NULL DEFAULT 0 CHECK (stock_mantenimiento >= 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL,
    deleted_by VARCHAR(100) NULL,
    CONSTRAINT check_stock_balance CHECK (stock_disponible + stock_en_obra + stock_mantenimiento = stock_total)
);

CREATE INDEX idx_equipos_busqueda ON public.equipos (codigo, categoria) WHERE estado = 'Activo' AND deleted_at IS NULL;

-- 3. TABLA ALQUILERES (CABECERA)
CREATE TABLE public.alquileres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consecutivo SERIAL UNIQUE,
    cliente_id BIGINT NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('COTIZACION', 'ACTIVO', 'FINALIZADO', 'CANCELADO')),
    subtotal_equipos NUMERIC(12, 2) NOT NULL DEFAULT 0,
    flete_entrega NUMERIC(12, 2) NOT NULL DEFAULT 0,
    flete_recogida NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal_general NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    deposito NUMERIC(12, 2) NOT NULL DEFAULT 0,
    garantia_monto NUMERIC(12, 2) NOT NULL DEFAULT 0,
    garantia_tipo VARCHAR(50) NOT NULL DEFAULT 'Efectivo',
    garantia_estado VARCHAR(50) NOT NULL DEFAULT 'Activa',
    observaciones TEXT,
    detalles_logistica TEXT,
    creado_por VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL,
    deleted_by VARCHAR(100) NULL
);

CREATE INDEX idx_alquileres_cliente_id ON public.alquileres (cliente_id);
CREATE INDEX idx_alquileres_estado ON public.alquileres (estado) WHERE deleted_at IS NULL;
CREATE INDEX idx_alquileres_consecutivo ON public.alquileres (consecutivo);

-- 4. TABLA LINEAS DE ALQUILER (DETALLE)
CREATE TABLE public.alquiler_detalles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alquiler_id BIGINT NOT NULL REFERENCES public.alquileres(id) ON DELETE CASCADE,
    equipo_id BIGINT NOT NULL REFERENCES public.equipos(id) ON DELETE RESTRICT,
    cantidad INT NOT NULL CHECK (cantidad > 0),
    tarifa_aplicada NUMERIC(12, 2) NOT NULL CHECK (tarifa_aplicada >= 0),
    dias_contratados INT NOT NULL CHECK (dias_contratados > 0),
    subtotal_linea NUMERIC(12, 2) NOT NULL CHECK (subtotal_linea >= 0),
    costo_dano NUMERIC(12, 2) NOT NULL DEFAULT 0,
    devuelto BOOLEAN NOT NULL DEFAULT FALSE,
    cantidad_devuelta INT NOT NULL DEFAULT 0,
    fecha_inicio TIMESTAMPTZ NOT NULL,
    fecha_fin TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_alquiler_detalles_alquiler_id ON public.alquiler_detalles (alquiler_id);
CREATE INDEX idx_alquiler_detalles_equipo_id ON public.alquiler_detalles (equipo_id);

-- 5. TABLA FACTURAS Y CUENTAS DE COBRO (PAGOS)
CREATE TABLE public.facturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_consecutivo SERIAL UNIQUE,
    tipo_documento VARCHAR(50) NOT NULL DEFAULT 'CUENTA_COBRO',
    alquiler_id BIGINT NOT NULL REFERENCES public.alquileres(id) ON DELETE RESTRICT,
    cliente_id BIGINT NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,
    subtotal NUMERIC(12, 2) NOT NULL,
    costos_dano NUMERIC(12, 2) NOT NULL DEFAULT 0,
    deposito_aplicado NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_pagar NUMERIC(12, 2) NOT NULL,
    estado_pago VARCHAR(30) NOT NULL DEFAULT 'EMITIDA' CHECK (estado_pago IN ('EMITIDA', 'PAGADA', 'ANULADA')),
    observaciones TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL,
    deleted_by VARCHAR(100) NULL
);

CREATE INDEX idx_facturas_alquiler_id ON public.facturas (alquiler_id);
CREATE INDEX idx_facturas_cliente_id ON public.facturas (cliente_id);
CREATE INDEX idx_facturas_estado ON public.facturas (estado_pago) WHERE deleted_at IS NULL;


-- ===========================
-- SEED DATA
-- ===========================

INSERT INTO public.clientes (nit_cedula, nombre, telefono, email, direccion, estado) VALUES
('1098703670', 'Yurgen Moreno', '3163323218', 'pezcaderia-sas@hotmail.com', 'Carrera 22 # 14 - 34 Bucaramanga', 'Activo'),
('901246730', 'La Pezcaderia SAS', '3004603379', 'pezcaderia-sas@hotmail.com', 'Carrera 22 # 14 - 34 Bucaramanga', 'Activo'),
('3209214544', 'MENZULY MARGARITA', '3209214544', '', 'CASA 10 MENZULY Bucaramanga', 'Activo'),
('60411293', 'LUIS FELIPE BALLESTEROS', '3209214544', '', 'CHIMITA Bucaramanga', 'Activo'),
('1098712831', 'DIEGO FERNANDO BARRERA CARREÑO', '3183951499', '', 'CALLE 22#19-28 Bucaramanga', 'Activo'),
('91246581', 'FERRETERIA JOSASE', '3164696524', '', 'CR 20#13-49 Bucaramanga', 'Activo'),
('91513844', 'NELSON MEJIA DIAZ', '3167033774', '', 'CALLE 14#20-47 Bucaramanga', 'Activo'),
('63314256', 'ANA FELICIA CASTELLANOS', '3204680070', '', 'CR 17#2E-16 B NORTE Bucaramanga', 'Activo'),
('60411293-9', 'LUZ YAMILE CASTELLANOS', '3052435985', '', 'RUITOQUE Floridablanca', 'Activo'),
('9005350161', 'JHON P&P', '3108588279', '', 'CR 35#34-24 Bucaramanga', 'Activo'),
('37277606', 'YURLEY MORENO', '3166031545', '', 'AV QUEBRADASECA#22-32 Bucaramanga', 'Activo'),
('3182544040', 'Hernando Rodriguez', '3182544040', '', 'Calle 11 # 22 - 02 Bucaramanga', 'Activo'),
('3210237252', 'Andres Joaquin Luna', '3210237252', '', 'Calle 33A # 24 - 37 Bucaramanga', 'Activo'),
('1007958917', 'Catalina bohorquez vergel', '3153470929', '', 'Cr 22#16-43 Bucaramanga', 'Activo'),
('9011448201', 'DIKAR INGENIERIA SAS', '3017021860', '', 'CR 7# 5 - 38 Bucaramanga', 'Activo'),
('9006256354', 'FUNDACION LVR GLOBAL', '3014454038', '', 'CR 53#68B - 125 CC GRAN CENTRO LC 2 Bucaramanga', 'Activo'),
('999999999', 'Cliente de Prueba Actualizado', '3001112233', 'test@test.com', 'Calle Falsa 123 Testlandia', 'Activo'),
('37843358', 'YESENIA LEON RUEDA', '6076436998', 'CONTABILIDAD@HOTELDELEONBUCARAMANGA', 'CALLE 56#21-49 Bucaramanga', 'Activo'),
('91493633', 'LUDWIN AGUILAR DELGADO', '3112184422', '', 'CR 21 # 18 -26 Bucaramanga', 'Activo'),
('91533576', 'GILBERTO RINCON SUESCUN', '3173674228', '', 'CALLE 16 # 25 - 30  CASA 8 Bucaramanga', 'Activo'),
('8902017769', 'IGLESIA BAUTISTA EL BUEN PASTOR', '3112112984', '', 'AV QUEBRADA SECA  # 22 -32 Bucaramanga', 'Activo'),
('193472392', 'HENRY CARVAJAL MARTINEZ', '3166242483', '', 'CR 16 # 17-66 Bucaramanga', 'Activo'),
('91291639', 'OSCAR CALDERON MORENO', '3164737310', '', 'CALLE 13 # 23-72 Bucaramanga', 'Activo'),
('1234', 'ROGER', '3142714833', '', 'CALLE 10A#16-51 Bucaramanga', 'Activo'),
('9693595', 'JESUS CABALLERO GELVEZ', '3217631089', '', 'CALLE 12 # 18 -30 Bucaramanga', 'Activo'),
('1099204815', 'YESID ROJAS', '3182012008', '', 'CALLE 54 # 34-21 Bucaramanga', 'Activo'),
('1102368767', 'CARLOS DAVID PEDRAZA', '3046198197', '', 'CR 35#48-67 Bucaramanga', 'Activo'),
('1015438644', 'SEBASTIAN CAMILO TORRES GALVIS', '3174754639', '', 'CR 36 # 48 -58 Bucaramanga', 'Activo'),
('39463199', 'LEYDIS JOHANNA ARCHILA LOPEZ', '3103287174', '', 'CALLE 46B # 5 - 07 VILLA DEL PRADO Bucaramanga', 'Activo'),
('1098604901', 'ADIEL SUAREZ', '3164547968', '', 'CR 35A # 54 -52 Bucaramanga', 'Activo'),
('901723152', 'ENMADERA STUDIO CREATIVO SAS', '3167428001', '', 'CALLE 46 # 0 - 225 Bucaramanga', 'Activo'),
('8902081921', 'SOCIEDAD MINERA SAN FRANCISCO S.A.S.', '3132713060', '', 'CR 24 # 29-04 Bucaramanga', 'Activo'),
('9003405281', 'BRING LTDA', '3209214544', '', 'CLL 36 # 22-16 BRR CENTRO Bucaramanga', 'Activo'),
('5696077', 'NELSON PICO', '3154517051', '', 'CALLE 18#26-14 Bucaramanga', 'Activo'),
('1001047015', 'SANTIAGO PAYARES', '3236523584', '', ' Bucaramanga', 'Activo'),
('915289374', 'ANDERSON SOLANO VILLAMIZAR', '3187394691', 'vtanlovimobiliario@gmail.com', 'CALLE 51A # 14 -110 Bucaramanga', 'Activo'),
('9014122408', 'GRUPO FERREMATE', '3012750613', '', ' Bucaramanga', 'Activo'),
('91445710', 'JULIO CESAR ROMERO', '3156889913', '', 'CR 55#51-87 Bucaramanga', 'Activo'),
('9018569235', 'GRUPO AGROINDUSTRIAL DE SANTANDER', '3176755886', 'grupoagroindustrialdesantander@gmail.com', 'FINCA LA SIBERIA ZARZAL LAS LAJAS Bucaramanga', 'Activo'),
('9010434582', 'SOLUCIONES INDUSTRIALES DYD SA', '3167821519', 'sisasdyd@gmail.com', 'CRA 25 N 18-39 Bucaramanga', 'Activo'),
('3182961313', 'LIZETH SUAREZ', '3182961313', '', 'CRA 27#17-35 Bucaramanga', 'Activo'),
('13542621', 'EDGAR CALDERON VILLAMIZAR', '3043866651', 'Edgarvillamizar79@gmail.com', 'CR 24 # 16-50 ED RIALTO Bucaramanga', 'Activo'),
('79043830', 'GUILLERMO GUEVARA', '3133027289', '', 'CALLE 12 # 26A -37 Bucaramanga', 'Activo'),
('13842798', 'HUGO MOJICA', '3118311152', '', 'CR 22 # 21 - 44 Bucaramanga', 'Activo'),
('1095950573', 'HELMER MAURICIO DAZA RODRIGEZ', '3202092679', '', 'DIAGONAL CAFE MADRID Bucaramanga', 'Activo'),
('999999999-46', 'Cliente de Prueba Actualizado', '3001112233', 'test@test.com', 'Calle Falsa 123 Testlandia', 'Activo'),
('1098751107', 'CAMILO SOLANO', '3187966581', '', 'VILLA MERCEDES Bucaramanga', 'Activo'),
('35253784', 'JULIA RODRIGEZ', '3158400049', '', 'REAL DE MINAS Bucaramanga', 'Activo'),
('91474319', 'EDIMER ROJAS SANCHEZ', '3174934985', '', 'CR 26#1A - 78 Bucaramanga', 'Activo'),
('1030536553', 'JAQUELIN GOMEZ', '3105730124', '', 'CENTRO COMERCIAL LA QUINTA Bucaramanga', 'Activo'),
('9009481478', 'PELLETCO', '3014851243', 'contacto@pelletco.com.co', 'VIA CORREDOR RIO FRIO CL 210 9 731 PAR INDUSTRIAL RIO FRIO Bucaramanga', 'Activo'),
('9019266446', 'IDIMCOL PROYECTOS INDUSTRIALES SAS', '3152434451', 'compras@idimcol.com', 'CR 13 # 23 -37 Bucaramanga', 'Activo'),
('9009768349', 'INGENIERIA Y DESARROLLOS INTEGRALES METALMECANICOS DE COLOMBIA SAS', '3164468484', '', 'CALLE 113 # 32 -79 TO 2 OF 102 Bucaramanga', 'Activo'),
('1098739043', 'JOSE HERNANDEZ FAYA', '3144462207', '', 'CR 15A#3-25 CHAPINERO Bucaramanga', 'Activo'),
('1098715149', 'YULY PAOLA GARCIA SANDOVAL', '3176689578', '', 'CALLE 35#12-59 Bucaramanga', 'Activo'),
('1098682238', 'JONATHAN LOZANO VILLAMIZAR', '3187394691', '', 'CR 30#34-84 GIRON Bucaramanga', 'Activo');

INSERT INTO public.equipos (codigo, nombre, categoria, tarifa_diaria, stock_total, stock_disponible, stock_en_obra, stock_mantenimiento, estado) VALUES
('SKU-001', 'ANDAMIO 1.50 X 1MT', 'Andamios', 2000, 10, 10, 0, 0, 'Activo'),
('SKU-002', 'Andamio 150x150', 'Andamios', 2000, 10, 10, 0, 0, 'Activo'),
('SKU-003', 'Cruceta', 'Andamios', 1000, 10, 10, 0, 0, 'Activo'),
('SKU-0004', 'Tablon', 'Andamios', 1000, 10, 10, 0, 0, 'Activo'),
('SKU-0005', 'Andamio 2 mt x 1mt', 'Andamios', 2000, 10, 10, 0, 0, 'Activo'),
('SKU-0006', 'Paral X 2 M', 'Andamios', 380, 10, 10, 0, 0, 'Activo'),
('SKU-0007', 'Paral x 4 M', 'Andamios', 380, 10, 10, 0, 0, 'Activo'),
('SKU-0008', 'Paral x 6 M', 'Andamios', 480, 10, 10, 0, 0, 'Activo'),
('SKU-0009', 'Cercha x 2 M', 'Andamios', 220, 10, 10, 0, 0, 'Activo'),
('SKU-0010', 'Cercha x 4 M', 'Andamios', 220, 10, 10, 0, 0, 'Activo'),
('SKU-0011', 'Rueda Andamio', 'Andamios', 1000, 10, 10, 0, 0, 'Activo'),
('SKU-0012', 'Cruceta andamio', 'Andamios', 500, 10, 10, 0, 0, 'Activo'),
('TEST-M1', 'Multi Test 1', 'PRUEBA', 100, 10, 10, 0, 0, 'Activo'),
('TEST-M2', 'Multi Test 2', 'PRUEBA', 200, 10, 10, 0, 0, 'Activo'),
('SKU-0000', 'prueba', 'Otros', 0, 10, 10, 0, 0, 'Activo'),
('SKU-0013', 'Tablero metalico 40Cm', 'Otros', 488, 10, 10, 0, 0, 'Activo'),
('SKU-0014', 'Tablero metalico 60Cm', 'Otros', 551, 10, 10, 0, 0, 'Activo'),
('SKU-0015', 'Tablero metalico 10CM', 'Otros', 299, 10, 10, 0, 0, 'Activo'),
('SKU-0016', 'Chapeta / Cucaracha', 'Otros', 38, 10, 10, 0, 0, 'Activo'),
('SKU-0017', 'Paral Metalico x 4Mt Alto', 'Andamios', 320, 10, 10, 0, 0, 'Activo'),
('SKU-0018', 'Paral Telescopico x 3 Mt Alto', 'Andamios', 536, 10, 10, 0, 0, 'Activo'),
('SKU-0019', 'ALINEADOR 3MT', 'Otros', 326, 10, 10, 0, 0, 'Activo'),
('SKU-0020', 'Tensores', 'Otros', 112, 10, 10, 0, 0, 'Activo'),
('SKU-0021', 'Cerchas x 3 Mt', 'Andamios', 200, 10, 10, 0, 0, 'Activo'),
('SKU-0022', 'Cerchas x 2 Mt', 'Andamios', 165, 10, 10, 0, 0, 'Activo'),
('SKU-0023', 'Angulo Corto x 60 Cm', 'Andamios', 105, 10, 10, 0, 0, 'Activo'),
('SKU-0024', 'Angulo Largo X 1,2 Mt', 'Andamios', 170, 10, 10, 0, 0, 'Activo'),
('SKU-0025', 'andamio 150x150', 'Andamios', 2000, 10, 10, 0, 0, 'Activo'),
('SKU-0026', 'TABLON ADICIONAL', 'ANDAMIO', 1000, 10, 10, 0, 0, 'Activo'),
('SKU-0027', 'POLEA', 'Andamios', 6000, 10, 10, 0, 0, 'Activo'),
('SKU-0028', 'ANGULO X 6 MT', 'Andamios', 1300, 10, 10, 0, 0, 'Activo'),
('SKU-0029', 'PASA MANOS', 'Andamios', 1500, 10, 10, 0, 0, 'Activo'),
('SKU-0030', 'TABLERO MADERA 70 X 140', 'Andamios', 600, 10, 10, 0, 0, 'Activo'),
('SKU-0031', 'ESCALERA TELESCOPICA 7.5 MT', 'Otros', 25000, 10, 10, 0, 0, 'Activo'),
('SKU-0032', 'TABLERO METALICO 30 CM', 'Andamios', 320, 10, 10, 0, 0, 'Activo'),
('SKU-0033', 'TABLERO METALICO 35 CM', 'Andamios', 400, 10, 10, 0, 0, 'Activo'),
('SKU-0034', 'ESCALERA TIJERA 3.MT', 'Andamios', 1, 10, 10, 0, 0, 'Activo'),
('SKU-0035', 'ESCALERA DE TIJERA', 'Otros', 20000, 10, 10, 0, 0, 'Activo'),
('SKU-0036', 'CERCHA 1.50', 'Andamios', 245, 10, 10, 0, 0, 'Activo'),
('SKU-0037', 'CERCHA 1.50', 'Andamios', 245, 10, 10, 0, 0, 'Activo'),
('SKU-0038', 'TABLERO METALICO 50 CM', 'Andamios', 610, 10, 10, 0, 0, 'Activo'),
('SKU-0039', 'TABLERO METALICO 25 CM', 'Andamios', 370, 10, 10, 0, 0, 'Activo'),
('SKU-0040', 'ALINEADOR 1.50 MT', 'Andamios', 350, 10, 10, 0, 0, 'Activo'),
('SKU-0041', 'ALINEADOR 2MT', 'Andamios', 497, 10, 10, 0, 0, 'Activo'),
('SKU-0042', 'ALINEADOR 3MT', 'Andamios', 497, 10, 10, 0, 0, 'Activo'),
('SKU-0043', 'ALINEADOR 6MT', 'Andamios', 497, 10, 10, 0, 0, 'Activo'),
('SKU-0044', 'ALINEADOR 6MT', 'Andamios', 497, 10, 10, 0, 0, 'Activo'),
('SKU-0045', 'ALINEADOR 6MT', 'Andamios', 497, 10, 10, 0, 0, 'Activo'),
('SKU-0046', 'ALINEADOR  4MT', 'Andamios', 497, 10, 10, 0, 0, 'Activo'),
('SKU-0047', 'ALINEADOR 4MT', 'Andamios', 280, 10, 10, 0, 0, 'Activo'),
('SKU-0048', 'TROMPO ELECTRICO 1/2 BULTO', 'Andamios', 90000, 10, 10, 0, 0, 'Activo'),
('SKU-0049', 'VIBRADOR CONCRETO', 'Andamios', 70000, 10, 10, 0, 0, 'Activo'),
('SKU-0050', 'RINCONERAS 120', 'Andamios', 550, 10, 10, 0, 0, 'Activo'),
('SKU-0051', 'RINCONERAS 60', 'Andamios', 550, 10, 10, 0, 0, 'Activo'),
('SKU-0052', 'PARAL 1 MT', 'Andamios', 320, 10, 10, 0, 0, 'Activo'),
('SKU-0053', 'PARAL 3MT', 'Andamios', 420, 10, 10, 0, 0, 'Activo');
