-- ============================================================================
-- MIGRACIÓN: Arquitectura Multi-Tenant SaaS, Aislamiento RLS y Trial Lifecycle
-- Proyecto: FerreOn ERP (alquileres-erp-nextjs)
-- Fecha: 2026-09-01
-- ============================================================================

-- 1. EXTENSIÓN CRIPTOGRÁFICA
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. TABLA CENTRAL DE EMPRESAS (TENANTS)
CREATE TABLE IF NOT EXISTS public.empresas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre VARCHAR(255) NOT NULL,
    nit VARCHAR(50),
    slug VARCHAR(100) UNIQUE NOT NULL,
    stripe_customer_id VARCHAR(100) UNIQUE,
    stripe_subscription_id VARCHAR(100),
    subscription_status VARCHAR(50) NOT NULL DEFAULT 'trialing' 
        CHECK (subscription_status IN ('trialing', 'active', 'past_due', 'canceled', 'unpaid')),
    plan_id VARCHAR(50) NOT NULL DEFAULT 'plan_monthly_flat',
    trial_ends_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '14 days'),
    configuracion JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_empresas_slug ON public.empresas (slug) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_empresas_stripe_customer ON public.empresas (stripe_customer_id);

-- 3. TABLA PIVOTE DE USUARIOS Y EMPRESAS (TENANT MEMBERSHIPS)
CREATE TABLE IF NOT EXISTS public.empresa_usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id UUID NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    rol VARCHAR(50) NOT NULL DEFAULT 'OPERADOR_BODEGA' 
        CHECK (rol IN ('SUPERADMIN', 'ADMIN', 'OPERADOR_BODEGA', 'VENDEDOR')),
    es_empresa_activa BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (empresa_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_empresa_usuarios_user_id ON public.empresa_usuarios (user_id);
CREATE INDEX IF NOT EXISTS idx_empresa_usuarios_empresa_id ON public.empresa_usuarios (empresa_id);

-- 4. TENANT PRINCIPAL INICIAL (MIGRACIÓN SEGURA DE DATOS HISTÓRICOS)
DO $$
DECLARE
    v_empresa_id UUID;
    v_user_record RECORD;
BEGIN
    -- Verificar si ya existe el tenant principal
    SELECT id INTO v_empresa_id FROM public.empresas WHERE slug = 'ferreon-principal';
    
    IF v_empresa_id IS NULL THEN
        INSERT INTO public.empresas (
            nombre, 
            nit, 
            slug, 
            subscription_status, 
            plan_id, 
            trial_ends_at
        ) VALUES (
            'FerreOn Equipos y Alquileres',
            '900123456-7',
            'ferreon-principal',
            'active',
            'plan_monthly_flat',
            NOW() + INTERVAL '365 days'
        ) RETURNING id INTO v_empresa_id;
    END IF;

    -- Asociar todos los usuarios existentes en auth.users a este tenant
    FOR v_user_record IN (SELECT id, raw_user_meta_data FROM auth.users) LOOP
        INSERT INTO public.empresa_usuarios (empresa_id, user_id, rol, es_empresa_activa)
        VALUES (
            v_empresa_id, 
            v_user_record.id, 
            COALESCE(v_user_record.raw_user_meta_data->>'rol', 'ADMIN'), 
            TRUE
        )
        ON CONFLICT (empresa_id, user_id) DO NOTHING;
    END LOOP;
END $$;

-- 5. FUNCIÓN HELPER DE RESOLUCIÓN DE TENANT ACTIVO
CREATE OR REPLACE FUNCTION public.get_current_tenant_id()
RETURNS UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT empresa_id 
    FROM public.empresa_usuarios 
    WHERE user_id = auth.uid() 
      AND es_empresa_activa = TRUE 
    LIMIT 1;
$$;

-- 6. ADICIÓN DE COLUMNA EMPRESA_ID CON DEFAULT AUTOMÁTICO EN TODAS LAS TABLAS

-- Clientes
ALTER TABLE public.clientes ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES public.empresas(id);
CREATE INDEX IF NOT EXISTS idx_clientes_empresa_id ON public.clientes (empresa_id);
ALTER TABLE public.clientes ALTER COLUMN empresa_id SET DEFAULT public.get_current_tenant_id();

-- Equipos
ALTER TABLE public.equipos ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES public.empresas(id);
CREATE INDEX IF NOT EXISTS idx_equipos_empresa_id ON public.equipos (empresa_id);
ALTER TABLE public.equipos ALTER COLUMN empresa_id SET DEFAULT public.get_current_tenant_id();

-- Alquileres
ALTER TABLE public.alquileres ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES public.empresas(id);
CREATE INDEX IF NOT EXISTS idx_alquileres_empresa_id ON public.alquileres (empresa_id);
ALTER TABLE public.alquileres ALTER COLUMN empresa_id SET DEFAULT public.get_current_tenant_id();

-- Alquiler Detalles
ALTER TABLE public.alquiler_detalles ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES public.empresas(id);
CREATE INDEX IF NOT EXISTS idx_alquiler_detalles_empresa_id ON public.alquiler_detalles (empresa_id);
ALTER TABLE public.alquiler_detalles ALTER COLUMN empresa_id SET DEFAULT public.get_current_tenant_id();

-- Facturas
ALTER TABLE public.facturas ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES public.empresas(id);
CREATE INDEX IF NOT EXISTS idx_facturas_empresa_id ON public.facturas (empresa_id);
ALTER TABLE public.facturas ALTER COLUMN empresa_id SET DEFAULT public.get_current_tenant_id();

-- Pagos
ALTER TABLE public.pagos ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES public.empresas(id);
CREATE INDEX IF NOT EXISTS idx_pagos_empresa_id ON public.pagos (empresa_id);
ALTER TABLE public.pagos ALTER COLUMN empresa_id SET DEFAULT public.get_current_tenant_id();

-- Idempotency Logs
ALTER TABLE public.idempotency_logs ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES public.empresas(id);
CREATE INDEX IF NOT EXISTS idx_idempotency_logs_empresa_id ON public.idempotency_logs (empresa_id);
ALTER TABLE public.idempotency_logs ALTER COLUMN empresa_id SET DEFAULT public.get_current_tenant_id();

-- 7. ASIGNACIÓN SEGURA DE DATOS HISTÓRICOS AL TENANT PRINCIPAL
DO $$
DECLARE
    v_empresa_id UUID;
BEGIN
    SELECT id INTO v_empresa_id FROM public.empresas WHERE slug = 'ferreon-principal';
    
    IF v_empresa_id IS NOT NULL THEN
        UPDATE public.clientes SET empresa_id = v_empresa_id WHERE empresa_id IS NULL;
        UPDATE public.equipos SET empresa_id = v_empresa_id WHERE empresa_id IS NULL;
        UPDATE public.alquileres SET empresa_id = v_empresa_id WHERE empresa_id IS NULL;
        UPDATE public.alquiler_detalles SET empresa_id = v_empresa_id WHERE empresa_id IS NULL;
        UPDATE public.facturas SET empresa_id = v_empresa_id WHERE empresa_id IS NULL;
        UPDATE public.pagos SET empresa_id = v_empresa_id WHERE empresa_id IS NULL;
        UPDATE public.idempotency_logs SET empresa_id = v_empresa_id WHERE empresa_id IS NULL;
    END IF;
END $$;

-- 8. POLÍTICAS ROW LEVEL SECURITY (RLS) MULTI-TENANT
ALTER TABLE public.empresas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.empresa_usuarios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "empresas_tenant_isolation" ON public.empresas;
CREATE POLICY "empresas_tenant_isolation" ON public.empresas
FOR ALL USING (
    id IN (SELECT empresa_id FROM public.empresa_usuarios WHERE user_id = auth.uid())
    OR auth.jwt() ->> 'role' = 'service_role'
);

DROP POLICY IF EXISTS "empresa_usuarios_tenant_isolation" ON public.empresa_usuarios;
CREATE POLICY "empresa_usuarios_tenant_isolation" ON public.empresa_usuarios
FOR ALL USING (
    empresa_id = public.get_current_tenant_id()
    OR user_id = auth.uid()
    OR auth.jwt() ->> 'role' = 'service_role'
);

ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "clientes_tenant_isolation" ON public.clientes;
CREATE POLICY "clientes_tenant_isolation" ON public.clientes
FOR ALL USING (
    empresa_id = public.get_current_tenant_id()
    OR auth.jwt() ->> 'role' = 'service_role'
);

ALTER TABLE public.equipos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "equipos_tenant_isolation" ON public.equipos;
CREATE POLICY "equipos_tenant_isolation" ON public.equipos
FOR ALL USING (
    empresa_id = public.get_current_tenant_id()
    OR auth.jwt() ->> 'role' = 'service_role'
);

ALTER TABLE public.alquileres ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "alquileres_tenant_isolation" ON public.alquileres;
CREATE POLICY "alquileres_tenant_isolation" ON public.alquileres
FOR ALL USING (
    empresa_id = public.get_current_tenant_id()
    OR auth.jwt() ->> 'role' = 'service_role'
);

ALTER TABLE public.alquiler_detalles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "alquiler_detalles_tenant_isolation" ON public.alquiler_detalles;
CREATE POLICY "alquiler_detalles_tenant_isolation" ON public.alquiler_detalles
FOR ALL USING (
    empresa_id = public.get_current_tenant_id()
    OR auth.jwt() ->> 'role' = 'service_role'
);

ALTER TABLE public.facturas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "facturas_tenant_isolation" ON public.facturas;
CREATE POLICY "facturas_tenant_isolation" ON public.facturas
FOR ALL USING (
    empresa_id = public.get_current_tenant_id()
    OR auth.jwt() ->> 'role' = 'service_role'
);

ALTER TABLE public.pagos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "pagos_tenant_isolation" ON public.pagos;
CREATE POLICY "pagos_tenant_isolation" ON public.pagos
FOR ALL USING (
    empresa_id = public.get_current_tenant_id()
    OR auth.jwt() ->> 'role' = 'service_role'
);

ALTER TABLE public.idempotency_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "idempotency_logs_tenant_isolation" ON public.idempotency_logs;
CREATE POLICY "idempotency_logs_tenant_isolation" ON public.idempotency_logs
FOR ALL USING (
    empresa_id = public.get_current_tenant_id()
    OR auth.jwt() ->> 'role' = 'service_role'
);

-- 9. ACTUALIZACIÓN DE RPC TRANSACCIONAL CON AISLAMIENTO Y VERIFICACIÓN DE SUSCRIPCIÓN
CREATE OR REPLACE FUNCTION public.crear_alquiler_transaccional(p_payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_tenant_id UUID;
    v_sub_status VARCHAR(50);
    v_trial_ends TIMESTAMPTZ;
    v_alquiler_id BIGINT;
    v_consecutivo INT;
    v_item JSONB;
    v_equipo_id BIGINT;
    v_cantidad INT;
    v_tarifa NUMERIC(12, 2);
    v_dias INT;
    v_subtotal_linea NUMERIC(12, 2);
    v_stock_disp INT;
    v_stock_obra INT;
    v_result JSONB;
BEGIN
    -- 1. Resolver Tenant ID activo
    v_tenant_id := public.get_current_tenant_id();
    
    -- Si se ejecuta vía service_role o payload específico, permitir fallback
    IF v_tenant_id IS NULL AND (p_payload->>'empresa_id') IS NOT NULL THEN
        v_tenant_id := (p_payload->>'empresa_id')::UUID;
    END IF;

    IF v_tenant_id IS NULL THEN
        -- Fallback al tenant principal
        SELECT id INTO v_tenant_id FROM public.empresas WHERE slug = 'ferreon-principal' LIMIT 1;
    END IF;

    -- 2. Validar Estado de Suscripción (Grace Period Enforcement)
    SELECT subscription_status, trial_ends_at 
    INTO v_sub_status, v_trial_ends
    FROM public.empresas 
    WHERE id = v_tenant_id;

    IF v_sub_status = 'trialing' AND v_trial_ends < NOW() THEN
        RAISE EXCEPTION 'El periodo de prueba de 14 días ha finalizado. Por favor regularice su suscripción para registrar nuevos alquileres.';
    END IF;

    IF v_sub_status IN ('canceled', 'unpaid', 'past_due') THEN
        RAISE EXCEPTION 'La suscripción de la empresa se encuentra inactiva (%) o en mora. Por favor actualice su método de pago.', v_sub_status;
    END IF;

    -- 3. Generar Consecutivo de Alquiler por Tenant
    SELECT COALESCE(MAX(consecutivo), 0) + 1 INTO v_consecutivo
    FROM public.alquileres
    WHERE empresa_id = v_tenant_id;

    -- 4. Insertar Cabecera de Alquiler vinculada al Tenant
    INSERT INTO public.alquileres (
        empresa_id,
        cliente_id,
        estado,
        consecutivo,
        flete_entrega,
        flete_recogida,
        deposito,
        garantia_monto,
        garantia_tipo,
        subtotal_general,
        total,
        saldo_pendiente,
        total_pagado,
        observaciones,
        detalles_logistica,
        fecha_entrega,
        fecha_devolucion_estimada,
        created_at,
        updated_at
    ) VALUES (
        v_tenant_id,
        (p_payload->>'clienteId')::BIGINT,
        COALESCE(p_payload->>'estado', 'ACTIVO'),
        v_consecutivo,
        COALESCE((p_payload->>'fleteEntrega')::NUMERIC, 0),
        COALESCE((p_payload->>'fleteRecogida')::NUMERIC, 0),
        COALESCE((p_payload->>'deposito')::NUMERIC, 0),
        COALESCE((p_payload->>'garantiaMonto')::NUMERIC, 0),
        COALESCE(p_payload->>'garantiaTipo', 'Efectivo'),
        COALESCE((p_payload->>'subtotalGeneral')::NUMERIC, (p_payload->>'totalEstimado')::NUMERIC, 0),
        COALESCE((p_payload->>'total')::NUMERIC, (p_payload->>'totalEstimado')::NUMERIC, 0),
        GREATEST(0, COALESCE((p_payload->>'total')::NUMERIC, 0) - COALESCE((p_payload->>'deposito')::NUMERIC, 0)),
        0,
        p_payload->>'observaciones',
        p_payload->>'detallesLogistica',
        COALESCE((p_payload->>'fechaEntrega')::TIMESTAMPTZ, NOW()),
        (p_payload->>'fechaDevolucionEstimada')::TIMESTAMPTZ,
        NOW(),
        NOW()
    ) RETURNING id INTO v_alquiler_id;

    -- 5. Procesar Ítems y Bloquear Stock de Equipos con FOR UPDATE
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_payload->'items') LOOP
        v_equipo_id := (v_item->>'equipoId')::BIGINT;
        v_cantidad := (v_item->>'cantidad')::INT;
        v_tarifa := (v_item->>'tarifaAplicada')::NUMERIC;
        v_dias := COALESCE((v_item->>'diasCobro')::INT, 1);
        v_subtotal_linea := COALESCE((v_item->>'subtotalLinea')::NUMERIC, v_cantidad * v_tarifa * v_dias);

        -- Bloqueo Pesimista del Equipo en el Tenant
        SELECT stock_disponible, stock_en_obra 
        INTO v_stock_disp, v_stock_obra
        FROM public.equipos
        WHERE id = v_equipo_id AND empresa_id = v_tenant_id
        FOR UPDATE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Equipo con ID % no encontrado en la empresa actual', v_equipo_id;
        END IF;

        IF v_stock_disp < v_cantidad THEN
            RAISE EXCEPTION 'Stock insuficiente para el equipo ID %. Disponible: %, Solicitado: %', v_equipo_id, v_stock_disp, v_cantidad;
        END IF;

        -- Actualizar Stock
        UPDATE public.equipos
        SET stock_disponible = stock_disponible - v_cantidad,
            stock_en_obra = stock_en_obra + v_cantidad,
            updated_at = NOW()
        WHERE id = v_equipo_id AND empresa_id = v_tenant_id;

        -- Insertar Detalle
        INSERT INTO public.alquiler_detalles (
            empresa_id,
            alquiler_id,
            equipo_id,
            cantidad,
            tarifa_aplicada,
            dias_cobro,
            subtotal_linea,
            fecha_inicio,
            fecha_fin_estimada,
            created_at,
            updated_at
        ) VALUES (
            v_tenant_id,
            v_alquiler_id,
            v_equipo_id,
            v_cantidad,
            v_tarifa,
            v_dias,
            v_subtotal_linea,
            COALESCE((v_item->>'fechaInicio')::TIMESTAMPTZ, NOW()),
            (v_item->>'fechaFinEstimada')::TIMESTAMPTZ,
            NOW(),
            NOW()
        );
    END LOOP;

    -- 6. Respuesta Estructurada
    SELECT jsonb_build_object(
        'success', true,
        'alquiler_id', v_alquiler_id,
        'consecutivo', v_consecutivo,
        'empresa_id', v_tenant_id,
        'message', 'Alquiler multi-tenant creado exitosamente con control de concurrencia'
    ) INTO v_result;

    RETURN v_result;
END;
$$;
