-- ============================================================================
-- MIGRACIÓN: Persistencia Relacional, Transaccionalidad ACID y Cartera
-- Proyecto: FerreOn ERP (alquileres-erp-nextjs)
-- Fecha: 2026-08-28
-- ============================================================================

-- 1. EXTENSIÓN DE COLUMNAS EN ALQUILERES PARA CONTROL DE SALDO
ALTER TABLE public.alquileres 
ADD COLUMN IF NOT EXISTS total_pagado NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE public.alquileres 
ADD COLUMN IF NOT EXISTS saldo_pendiente NUMERIC(12, 2) NOT NULL DEFAULT 0;

-- 2. TABLA DE RECAUDOS / PAGOS DE CARTERA
CREATE TABLE IF NOT EXISTS public.pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alquiler_id BIGINT NOT NULL REFERENCES public.alquileres(id) ON DELETE RESTRICT,
    cliente_id BIGINT NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,
    monto NUMERIC(12, 2) NOT NULL CHECK (monto > 0),
    metodo_pago VARCHAR(50) NOT NULL CHECK (metodo_pago IN ('TRANSFERENCIA', 'EFECTIVO', 'NEQUI', 'DAVIPLATA', 'CHEQUE')),
    referencia VARCHAR(100),
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    registrado_por VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL,
    deleted_by VARCHAR(100) NULL
);

CREATE INDEX IF NOT EXISTS idx_pagos_alquiler_id ON public.pagos (alquiler_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_pagos_cliente_id ON public.pagos (cliente_id) WHERE deleted_at IS NULL;

-- 3. TRIGGER DE SINCRONIZACIÓN FINANCIERA AUTOMÁTICA
CREATE OR REPLACE FUNCTION public.fn_actualizar_saldo_alquiler_y_factura()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_alquiler_id BIGINT;
    v_total_pagado NUMERIC(12, 2);
    v_total_contrato NUMERIC(12, 2);
    v_deposito NUMERIC(12, 2);
    v_saldo NUMERIC(12, 2);
BEGIN
    v_alquiler_id := COALESCE(NEW.alquiler_id, OLD.alquiler_id);

    -- Calcular sumatoria real de abonos activos
    SELECT COALESCE(SUM(monto), 0) INTO v_total_pagado
    FROM public.pagos
    WHERE alquiler_id = v_alquiler_id AND deleted_at IS NULL;

    -- Obtener valores totales del contrato
    SELECT total, COALESCE(deposito, 0) INTO v_total_contrato, v_deposito
    FROM public.alquileres
    WHERE id = v_alquiler_id;

    -- Saldo pendiente = Total - Depósito - Total Pagado
    v_saldo := GREATEST(0, v_total_contrato - v_deposito - v_total_pagado);

    -- Actualizar cabecera del contrato
    UPDATE public.alquileres
    SET total_pagado = v_total_pagado,
        saldo_pendiente = v_saldo,
        updated_at = NOW()
    WHERE id = v_alquiler_id;

    -- Actualizar estado de cuenta de cobro / factura si el saldo es cero
    IF v_saldo <= 0 THEN
        UPDATE public.facturas
        SET estado_pago = 'PAGADA',
            updated_at = NOW()
        WHERE alquiler_id = v_alquiler_id;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_actualizar_saldo_alquiler ON public.pagos;
CREATE TRIGGER trg_actualizar_saldo_alquiler
AFTER INSERT OR UPDATE OR DELETE ON public.pagos
FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_saldo_alquiler_y_factura();

-- 4. PROCEDIMIENTO RPC TRANSACCIONAL: CREAR ALQUILER CON FOR UPDATE
CREATE OR REPLACE FUNCTION public.crear_alquiler_transaccional(p_payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_alquiler_id BIGINT;
    v_consecutivo INT;
    v_item JSONB;
    v_equipo_id BIGINT;
    v_cantidad INT;
    v_tarifa NUMERIC(12, 2);
    v_dias INT;
    v_subtotal_linea NUMERIC(12, 2);
    v_stock_disp INT;
    v_stock_obra INT;
    v_result JSONB;
BEGIN
    -- 1. Insertar Cabecera de Alquiler
    INSERT INTO public.alquileres (
        cliente_id,
        estado,
        subtotal_equipos,
        flete_entrega,
        flete_recogida,
        subtotal_general,
        total,
        deposito,
        garantia_monto,
        garantia_tipo,
        garantia_estado,
        total_pagado,
        saldo_pendiente,
        observaciones,
        detalles_logistica,
        creado_por
    ) VALUES (
        (p_payload->>'cliente_id')::BIGINT,
        COALESCE(p_payload->>'estado', 'ACTIVO'),
        (p_payload->>'subtotal_equipos')::NUMERIC,
        COALESCE((p_payload->>'flete_entrega')::NUMERIC, 0),
        COALESCE((p_payload->>'flete_recogida')::NUMERIC, 0),
        (p_payload->>'subtotal_general')::NUMERIC,
        (p_payload->>'total')::NUMERIC,
        COALESCE((p_payload->>'deposito')::NUMERIC, 0),
        COALESCE((p_payload->>'garantia_monto')::NUMERIC, 0),
        COALESCE(p_payload->>'garantia_tipo', 'Efectivo'),
        'Activa',
        0,
        GREATEST(0, (p_payload->>'total')::NUMERIC - COALESCE((p_payload->>'deposito')::NUMERIC, 0)),
        p_payload->>'observaciones',
        p_payload->>'detalles_logistica',
        p_payload->>'creado_por'
    )
    RETURNING id, consecutivo INTO v_alquiler_id, v_consecutivo;

    -- 2. Procesar cada renglón de equipo con bloqueo a nivel de fila (FOR UPDATE)
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_payload->'items')
    LOOP
        v_equipo_id := (v_item->>'equipo_id')::BIGINT;
        v_cantidad := (v_item->>'cantidad')::INT;
        v_tarifa := (v_item->>'tarifa_aplicada')::NUMERIC;
        v_dias := (v_item->>'dias_contratados')::INT;
        v_subtotal_linea := v_cantidad * v_tarifa * v_dias;

        -- Bloqueo FOR UPDATE en tabla de equipos
        SELECT stock_disponible, stock_en_obra INTO v_stock_disp, v_stock_obra
        FROM public.equipos
        WHERE id = v_equipo_id
        FOR UPDATE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Equipo no encontrado en catálogo (ID: %)', v_equipo_id;
        END IF;

        IF v_stock_disp < v_cantidad THEN
            RAISE EXCEPTION 'Stock insuficiente para el equipo ID %. Disponible: %, Solicitado: %', v_equipo_id, v_stock_disp, v_cantidad;
        END IF;

        -- Descontar stock disponible e incrementar stock en obra atómicamente
        UPDATE public.equipos
        SET stock_disponible = stock_disponible - v_cantidad,
            stock_en_obra = stock_en_obra + v_cantidad,
            updated_at = NOW()
        WHERE id = v_equipo_id;

        -- Insertar línea de detalle
        INSERT INTO public.alquiler_detalles (
            alquiler_id,
            equipo_id,
            cantidad,
            tarifa_aplicada,
            dias_contratados,
            subtotal_linea,
            fecha_inicio,
            fecha_fin,
            devuelto,
            cantidad_devuelta,
            costo_dano
        ) VALUES (
            v_alquiler_id,
            v_equipo_id,
            v_cantidad,
            v_tarifa,
            v_dias,
            v_subtotal_linea,
            COALESCE((v_item->>'fecha_inicio')::TIMESTAMPTZ, NOW()),
            (v_item->>'fecha_fin')::TIMESTAMPTZ,
            FALSE,
            0,
            0
        );
    END LOOP;

    -- 3. Retornar payload del contrato creado
    SELECT json_build_object(
        'id', a.id,
        'consecutivo', a.consecutivo,
        'cliente_id', a.cliente_id,
        'estado', a.estado,
        'total', a.total,
        'deposito', a.deposito,
        'saldo_pendiente', a.saldo_pendiente,
        'created_at', a.created_at
    )::JSONB INTO v_result
    FROM public.alquileres a
    WHERE a.id = v_alquiler_id;

    RETURN v_result;
END;
$$;

-- 5. PROCEDIMIENTO RPC: PROCESAR DEVOLUCIÓN PARCIAL / TOTAL Y RESTITUIR STOCK
CREATE OR REPLACE FUNCTION public.procesar_devolucion_alquiler(p_payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_alquiler_id BIGINT;
    v_item JSONB;
    v_detalle_id BIGINT;
    v_equipo_id BIGINT;
    v_cant_devuelta INT;
    v_costo_dano NUMERIC(12, 2);
    v_cant_actual INT;
    v_cant_total INT;
    v_pendientes INT;
    v_result JSONB;
BEGIN
    v_alquiler_id := (p_payload->>'alquiler_id')::BIGINT;

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_payload->'devoluciones')
    LOOP
        v_detalle_id := (v_item->>'detalle_id')::BIGINT;
        v_cant_devuelta := (v_item->>'cantidad_devuelta')::INT;
        v_costo_dano := COALESCE((v_item->>'costo_dano')::NUMERIC, 0);

        -- Bloqueo y verificación de línea de detalle
        SELECT equipo_id, cantidad, cantidad_devuelta INTO v_equipo_id, v_cant_total, v_cant_actual
        FROM public.alquiler_detalles
        WHERE id = v_detalle_id AND alquiler_id = v_alquiler_id
        FOR UPDATE;

        IF FOUND AND v_cant_devuelta > 0 THEN
            -- Actualizar detalle
            UPDATE public.alquiler_detalles
            SET cantidad_devuelta = cantidad_devuelta + v_cant_devuelta,
                devuelto = (cantidad_devuelta + v_cant_devuelta >= cantidad),
                costo_dano = costo_dano + v_costo_dano
            WHERE id = v_detalle_id;

            -- Restituir stock disponible y reducir stock en obra
            UPDATE public.equipos
            SET stock_disponible = stock_disponible + v_cant_devuelta,
                stock_en_obra = GREATEST(0, stock_en_obra - v_cant_devuelta),
                updated_at = NOW()
            WHERE id = v_equipo_id;
        END IF;
    END LOOP;

    -- Verificar si quedan renglones pendientes por devolver
    SELECT COUNT(*) INTO v_pendientes
    FROM public.alquiler_detalles
    WHERE alquiler_id = v_alquiler_id AND devuelto = FALSE;

    IF v_pendientes = 0 THEN
        UPDATE public.alquileres
        SET estado = 'FINALIZADO',
            updated_at = NOW()
        WHERE id = v_alquiler_id;
    END IF;

    SELECT json_build_object(
        'success', TRUE,
        'alquiler_id', v_alquiler_id,
        'finalizado', (v_pendientes = 0)
    )::JSONB INTO v_result;

    RETURN v_result;
END;
$$;

-- 6. POLÍTICAS RLS PARA TABLA PAGOS
ALTER TABLE public.pagos ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'pagos' AND policyname = 'Permitir todo en pagos'
    ) THEN
        CREATE POLICY "Permitir todo en pagos" ON public.pagos
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
